# Generated by Django 3.1.6 on 2021-02-10 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.ManyToManyField(help_text='Select a Language for this Book', to='catalog.Language'),
        ),
    ]
