# Generated by Django 3.1.6 on 2021-02-15 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20210210_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='release',
            field=models.DateField(help_text='Enter Release Date', null=True),
        ),
    ]
