# Generated by Django 3.1.6 on 2021-02-15 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_book_release'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='release',
            field=models.DateField(blank=True, help_text='Enter Release Date', null=True),
        ),
    ]
